# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

start_profiler <- function(str) {
    .Call(`_randomPlantedForest_start_profiler`, str)
}

stop_profiler <- function() {
    .Call(`_randomPlantedForest_stop_profiler`)
}

